insert into lineas (linea,color)
values
("Linea 1","rosa"),
("Linea 2","azul"),
("Linea 3","verde amarillo"),
("Linea 4","azul agua"),
("Linea 5","amarillo"),
("Linea 6","rojo"),
("Linea 7","naranja"),
("Linea 8","verde"),
("Linea 9","cafe"),
("Linea A","morado"),
("Linea B","verde y gris"),
("Linea 12","dorado");

insert into estaciones (estacion,linea_id)
values
("Observatorio",1),
("Tacubaya",1),
("Juanacatán",1),
("Chapultepec",1),
("Sevilla",1),
("Insurgentes",1),
("Cuauhtémoc",1),
("Balderas",1),
("Salto del Agua",1),
("Isabel la Católica",1),
("Pino Suarez",1),
("Merced",1),
("Candelaria",1),
("San Lázoro",1),
("Moctezuma",1),
("Balbuena",1),
("Boulevard Pto. Aéreo",1),
("Gómez Farías",1),
("Zaragoza",1),
("Pantitlán",1),

("Tasqueña",2),
("Ermita",2),
("Portales",2),
("Nativitas",2),
("Villa de Cortes",2),
("Xola",2),
("Viaducto",2),
("Chabacano",2),
("San Antonio Abad",2),
("Pino Suarez",2),
("Zócalo",2),
("Allende",2),
("Bellas Artes",2),
("Hidalgo",2),
("Revolución",2),
("San Cosme",2),
("Normal",2),
("Popotla",2),
("Cuitláhuac",2),
("Tacuba",2),
("Panteones",2),
("Cuatro Caminos",2),

("Universidad",3),
("Copilco",3),
("Miguel Ángel de Quevedo",3),
("Viveros / Derechos Humanos",3),
("Coyoacán",3),
("Zapata",3),
("División del Norte",3),
("Eugenía",3),
("Etiopía / Plaza de la Transparencia",3),
("Centro Médico",3),
("Hospital General",3),
("Niños Héroes",3),
("Balderas",3),
("Juárez",3),
("Hidalgo",3),
("Guerrero",3),
("Tlatelolco",3),
("Potrero",3),
("Deportivo 18 de Marzo",3),
("Indios Verdes",3),

("Santa Anita", 4 ),
("Jamaica", 4 ),
("Fray Servando", 4 ),
("Candelaria", 4 ),
("Morelos", 4 ),
("Canal del Norte", 4 ),
("Consulado", 4 ),
("Bondojito", 4 ),
("Talismán", 4 ),
("Martín Carrera", 4 ),

("Pantitlán", 5 ),
("Hangares", 5 ),
("Terminal Aérea", 5 ),
("Oceanía", 5 ),
("Aragón", 5 ),
("Eduardo Molina", 5 ),
("Consulado", 5 ),
("Valle Gómez", 5 ),
("La Raza", 5 ),
("Autobuses del Norte", 5 ),
("Instituto del Petróleo", 5 ),
("Politécnico", 5 ),

("El Rosario", 6),
("Tezozómoc", 6),
("Azcapotzalco", 6),
("Ferrería / Arena Ciudad de México", 6),
("Norte 45", 6),
("Vallejo", 6),
("Instituto del Petróleo", 6),
("Lindavista", 6),
("Deportivo 18 de Marzo", 6),
("Martín Carrera", 6),

("Barranca del Muerto",7),
("Insurgentes Sur",7),
("Sn. Antonio",7),
("Sn. Pedro de los Pinos",7),
("Tacubaya",7),
("Constituyentes",7),
("Auditorio",7),
("Polanco",7),
("San Joaquín",7),
("Tacuba",7),
("Refinería",7),
("Camarones",7),
("Aquiles Serdán",7),
("El Rosario",7),

("Tacubaya",8),
("Patriotismo",8),
("Chilpancingo",8),
("Centro Médico",8),
("Lázaro Cárdenas",8),
("Chabacano",8),
("Jamaica",8),
("Mixiuhca",8),
("Velódromo",8),
("Ciudad Deportiva",8),
("Puebla",8),
("Pantitlán",8),

("Tacubaya", 9 ),
("Patriotismo", 9 ),
("Chilpancingo", 9 ),
("Centro Médico", 9 ),
("Lázaro Cárdenas", 9 ),
("Chabacano", 9 ),
("Jamaica", 9 ),
("Mixiuhca", 9 ),
("Velódromo", 9 ),
("Ciudad Deportiva", 9 ),
("Puebla", 9 ),
("Pantitlán", 9 ),

("Pantitlán", 10),
("Agrícola Oriental", 10),
("Canal de San Juan", 10),
("Tepalcates", 10),
("Guelatao", 10),
("Peñón viejo", 10),
("Acatitla", 10),
("Santa Marta", 10),
("Los Reyes", 10),
("La Paz", 10),

("Buenavista", 11 ),
("Guerrero", 11 ),
("Garibaldi / Lagunilla", 11 ),
("Lagunilla", 11 ),
("Tepito", 11 ),
("Morelos", 11 ),
("San Lázaro", 11 ),
("Flores Magón", 11 ),
("Romero Rubio", 11 ),
("Oceanía", 11 ),
("Depórtivo Oceanía", 11 ),
("Villa de Aragón", 11 ),
("Nezahualcóyotl", 11 ),
("Impulsora", 11 ),
("Río de los Remedios", 11 ),
("Múzquiz", 11 ),
("Ecatepec", 11 ),
("Olímpica", 11 ),
("Plaza Aragón", 11 ),
("Ciudad Azteca", 11 ),

("Mixcoac", 12),
("Insurgentes Sur", 12),
("Hospital 20 de Noviembre", 12),
("Zapata", 12),
("Parque de los Venados", 12),
("Eje Central", 12),
("Ermita", 12),
("Mexicaltzingo", 12),
("Atlalilco", 12),
("Culhuacán", 12),
("San Andrés Tomatlán", 12),
("Lomas Estrella", 12),
("Calle 11", 12),
("Periférico Ote.", 12),
("Tezonco", 12),
("Olivos", 12),
("Nopalera", 12),
("Zapotitlán", 12),
("Tlaltenco", 12),
("Tláhuac", 12);