insert into estaciones (ruta_logo)
values
("ic_ic_Observatorio"),
("ic_Tacubaya"),
("ic_Juanacatán"),
("ic_Chapultepec"),
("ic_Sevilla"),
("ic_Insurgentes"),
("ic_Cuauhtémoc"),
("ic_Balderas"),
("ic_Salto del Agua"),
("ic_Isabel la Católica"),
("ic_Pino Suarez"),
("ic_Merced"),
("ic_Candelaria"),
("ic_San Lázoro"),
("ic_Moctezuma"),
("ic_balbuena"),
("ic_boulevard_pto_aereo"),
("ic_Gómez Farías"),
("ic_Zaragoza"),
("ic_Pantitlán"),

("ic_Tasqueña",2),
("ic_Ermita",2),
("ic_Portales",2),
("ic_Nativitas",2),
("ic_Villa de Cortes",2),
("ic_Xola",2),
("ic_Viaducto",2),
("ic_Chabacano",2),
("ic_San Antonio Abad",2),
("ic_Pino Suarez",2),
("ic_Zócalo",2),
("ic_Allende",2),
("ic_Bellas Artes",2),
("ic_Hidalgo",2),
("ic_Revolución",2),
("ic_San Cosme",2),
("ic_Normal",2),
("ic_Popotla",2),
("ic_Cuitláhuac",2),
("ic_Tacuba",2),
("ic_Panteones",2),
("ic_Cuatro Caminos",2),

("ic_Universidad",3),
("ic_Copilco",3),
("ic_Miguel Ángel de Quevedo",3),
("ic_Viveros / Derechos Humanos",3),
("ic_Coyoacán",3),
("ic_Zapata",3),
("ic_División del Norte",3),
("ic_Eugenía",3),
("ic_Etiopía / Plaza de la Transparencia",3),
("ic_Centro Médico",3),
("ic_Hospital General",3),
("ic_Niños Héroes",3),
("ic_Balderas",3),
("ic_Juárez",3),
("ic_Hidalgo",3),
("ic_Guerrero",3),
("ic_Tlatelolco",3),
("ic_Potrero",3),
("ic_Deportivo 18 de Marzo",3),
("ic_Indios Verdes",3),

("ic_Santa Anita", 4 ),
("ic_Jamaica", 4 ),
("ic_Fray Servando", 4 ),
("ic_Candelaria", 4 ),
("ic_Morelos", 4 ),
("ic_Canal del Norte", 4 ),
("ic_Consulado", 4 ),
("ic_Bondojito", 4 ),
("ic_Talismán", 4 ),
("ic_Martín Carrera", 4 ),

("ic_Pantitlán", 5 ),
("ic_Hangares", 5 ),
("ic_Terminal Aérea", 5 ),
("ic_Oceanía", 5 ),
("ic_Aragón", 5 ),
("ic_Eduardo Molina", 5 ),
("ic_Consulado", 5 ),
("ic_Valle Gómez", 5 ),
("ic_La Raza", 5 ),
("ic_Autobuses del Norte", 5 ),
("ic_Instituto del Petróleo", 5 ),
("ic_Politécnico", 5 ),

("ic_El Rosario", 6),
("ic_Tezozómoc", 6),
("ic_Azcapotzalco", 6),
("ic_Ferrería / Arena Ciudad de México", 6),
("ic_Norte 45", 6),
("ic_Vallejo", 6),
("ic_Instituto del Petróleo", 6),
("ic_Lindavista", 6),
("ic_Deportivo 18 de Marzo", 6),
("ic_Martín Carrera", 6),

("ic_Barranca del Muerto",7),
("ic_Insurgentes Sur",7),
("ic_Sn. Antonio",7),
("ic_Sn. Pedro de los Pinos",7),
("ic_Tacubaya",7),
("ic_Constituyentes",7),
("ic_Auditorio",7),
("ic_Polanco",7),
("ic_San Joaquín",7),
("ic_Tacuba",7),
("ic_Refinería",7),
("ic_Camarones",7),
("ic_Aquiles Serdán",7),
("ic_El Rosario",7),

("ic_Tacubaya",8),
("ic_Patriotismo",8),
("ic_Chilpancingo",8),
("ic_Centro Médico",8),
("ic_Lázaro Cárdenas",8),
("ic_Chabacano",8),
("ic_Jamaica",8),
("ic_Mixiuhca",8),
("ic_Velódromo",8),
("ic_Ciudad Deportiva",8),
("ic_Puebla",8),
("ic_Pantitlán",8),

("ic_Tacubaya", 9 ),
("ic_Patriotismo", 9 ),
("ic_Chilpancingo", 9 ),
("ic_Centro Médico", 9 ),
("ic_Lázaro Cárdenas", 9 ),
("ic_Chabacano", 9 ),
("ic_Jamaica", 9 ),
("ic_Mixiuhca", 9 ),
("ic_Velódromo", 9 ),
("ic_Ciudad Deportiva", 9 ),
("ic_Puebla", 9 ),
("ic_Pantitlán", 9 ),

("ic_Pantitlán", 10),
("ic_Agrícola Oriental", 10),
("ic_Canal de San Juan", 10),
("ic_Tepalcates", 10),
("ic_Guelatao", 10),
("ic_Peñón viejo", 10),
("ic_Acatitla", 10),
("ic_Santa Marta", 10),
("ic_Los Reyes", 10),
("ic_La Paz", 10),

("ic_Buenavista", 11 ),
("ic_Guerrero", 11 ),
("ic_Garibaldi / Lagunilla", 11 ),
("ic_Lagunilla", 11 ),
("ic_Tepito", 11 ),
("ic_Morelos", 11 ),
("ic_San Lázaro", 11 ),
("ic_Flores Magón", 11 ),
("ic_Romero Rubio", 11 ),
("ic_Oceanía", 11 ),
("ic_Depórtivo Oceanía", 11 ),
("ic_Villa de Aragón", 11 ),
("ic_Nezahualcóyotl", 11 ),
("ic_Impulsora", 11 ),
("ic_Río de los Remedios", 11 ),
("ic_Múzquiz", 11 ),
("ic_Ecatepec", 11 ),
("ic_Olímpica", 11 ),
("ic_Plaza Aragón", 11 ),
("ic_Ciudad Azteca", 11 ),

("ic_Mixcoac", 12),
("ic_Insurgentes Sur", 12),
("ic_Hospital 20 de Noviembre", 12),
("ic_Zapata", 12),
("ic_Parque de los Venados", 12),
("ic_Eje Central", 12),
("ic_Ermita", 12),
("ic_Mexicaltzingo", 12),
("ic_Atlalilco", 12),
("ic_Culhuacán", 12),
("ic_San Andrés Tomatlán", 12),
("ic_Lomas Estrella", 12),
("ic_Calle 11", 12),
("ic_Periférico Ote.", 12),
("ic_Tezonco", 12),
("ic_Olivos", 12),
("ic_Nopalera", 12),
("ic_Zapotitlán", 12),
("ic_Tlaltenco", 12),
("ic_Tláhuac", 12);