insert into lineas (linea,color)
values
("Línea 1","rosa"),
("Línea 2","azul"),
("Línea 3","verde amarillo"),
("Línea 4","azul agua"),
("Línea 5","amarillo"),
("Línea 6","rojo"),
("Línea 7","naranja"),
("Línea 8","verde"),
("Línea 9","cafe"),
("Línea A","morado"),
("Línea B","verde y gris"),
("Línea 12","dorado");

insert into estaciones (linea_id, estacion, ruta_logo)
values
(1,"Observatorio","ic_observatorio"),
(1,"Tacubaya","ic_tacubaya"),
(1,"Juanacatán","ic_juanacatan"),
(1,"Chapultepec","ic_chapultepec"),
(1,"Sevilla","ic_sevilla"),
(1,"Insurgentes","ic_insurgentes"),
(1,"Cuauhtémoc","ic_cuauhtemoc"),
(1,"Balderas","ic_balderas"),
(1,"Salto del Agua","ic_salto_del_agua"),
(1,"Isabel la Católica","ic_isabel_catolica"),
(1,"Pino Suarez","ic_pino_suarez"),
(1,"Merced","ic_merced"),
(1,"Candelaria","ic_candelaria"),
(1,"San Lázoro","ic_san_lazoro"),
(1,"Moctezuma","ic_moctezuma"),
(1,"Balbuena","ic_balbuena"),
(1,"Boulevard Pto. Aéreo","ic_boulevard_aereo"),
(1,"Gómez Farías","ic_gomez_farias"),
(1,"Zaragoza","ic_zaragoza"),
(1,"Pantitlán","ic_pantitan"),
(2,"Tasqueña","ic_tasqueña"),
(2,"Ermita","ic_ermita"),
(2,"Portales","ic_portales"),
(2,"Nativitas","ic_nativitas"),
(2,"Villa de Cortes","ic_villa_de_cortes"),
(2,"Xola","ic_xola"),
(2,"Viaducto","ic_viaducto"),
(2,"Chabacano","ic_chabacano"),
(2,"San Antonio Abad","ic_san_antonio_abad"),
(2,"Pino Suarez","ic_pino_suarez"),
(2,"Zócalo","ic_zocalo"),
(2,"Allende","ic_allende"),
(2,"Bellas Artes","ic_bellas_artes"),
(2,"Hidalgo","ic_hidalgo"),
(2,"Revolución","ic_revolucion"),
(2,"San Cosme","ic_san_cosme"),
(2,"Normal","ic_normal"),
(2,"Popotla","ic_popotla"),
(2,"Cuitláhuac","ic_cuitlahuac"),
(2,"Tacuba","ic_tacuba"),
(2,"Panteones","ic_panteones"),
(2,"Cuatro Caminos","ic_cuatro_caminos"),
(3,"Universidad","ic_universidad"),
(3,"Copilco","ic_copilco"),
(3,"Miguel Ángel de Quevedo","ic_miguel_a_quevedo"),
(3,"Viveros / Derechos Humanos","ic_viveros_d_humanos"),
(3,"Coyoacán","ic_coyoacan"),
(3,"Zapata","ic_zapata"),
(3,"División del Norte","ic_division_norte"),
(3,"Eugenía","ic_eugenia"),
(3,"Etiopía / Plaza de la Transparencia","ic_etiopia_transparencia"),
(3,"Centro Médico","ic_centro_medico"),
(3,"Hospital General","ic_hospital_general"),
(3,"Niños Héroes","ic_ñinos_heroes"),
(3,"Balderas","ic_balderas"),
(3,"Juárez","ic_juarez"),
(3,"Hidalgo","ic_hidalgo"),
(3,"Guerrero","ic_guerrero"),
(3,"Tlatelolco","ic_tlatelolco"),
(3,"Potrero","ic_potrero"),
(3,"Deportivo 18 de Marzo","ic_deportivo_18_marzo"),
(3,"Indios Verdes","ic_indios_verdes"),
(4,"Santa Anita","ic_santa_anita"),
(4,"Jamaica","ic_jamaica"),
(4,"Fray Servando","ic_fray_servando"),
(4,"Candelaria","ic_candelaria"),
(4,"Morelos","ic_morelos"),
(4,"Canal del Norte","ic_canal_del_norte"),
(4,"Consulado","ic_consulado"),
(4,"Bondojito","ic_bondojito"),
(4,"Talismán","ic_talisman"),
(4,"Martín Carrera","ic_martin_carrera"),
(5,"Pantitlán","ic_pantitlan"),
(5,"Hangares","ic_hangares"),
(5,"Terminal Aérea","ic_terminal_aerea"),
(5,"Oceanía","ic_oceania"),
(5,"Aragón","ic_aragon"),
(5,"Eduardo Molina","ic_eduardo_molina"),
(5,"Consulado","ic_consulado"),
(5,"Valle Gómez","ic_valle_gomez"),
(5,"La Raza","ic_la_raza"),
(5,"Autobuses del Norte","ic_autobuses_del_norte"),
(5,"Instituto del Petróleo","ic_instituto_del_petroleo"),
(5,"Politécnico","ic_politecnico"),
(6,"El Rosario","ic_el_rosario"),
(6,"Tezozómoc","ic_tezozomoc"),
(6,"Azcapotzalco","ic_azcapotzalco"),
(6,"Ferrería / Arena Ciudad de México","ic_ferreria_arena_cdmx"),
(6,"Norte 45","ic_norte_45"),
(6,"Vallejo","ic_vallejo"),
(6,"Instituto del Petróleo","ic_instituto_del_petroleo"),
(6,"Lindavista","ic_lindavista"),
(6,"Deportivo 18 de Marzo","ic_deportivo_18_marzo"),
(6,"Martín Carrera","ic_martin_carrera"),
(7,"Barranca del Muerto","ic_barranca_muerto"),
(7,"Insurgentes Sur","ic_insurgentes_sur"),
(7,"Sn. Antonio","ic_sn_antonio"),
(7,"Sn. Pedro de los Pinos","ic_sn_pedro_pinos"),
(7,"Tacubaya","ic_tacubaya"),
(7,"Constituyentes","ic_constituyentes"),
(7,"Auditorio","ic_auditorio"),
(7,"Polanco","ic_polanco"),
(7,"San Joaquín","ic_san_joaquin"),
(7,"Tacuba","ic_tacuba"),
(7,"Refinería","ic_refineria"),
(7,"Camarones","ic_camarones"),
(7,"Aquiles Serdán","ic_aquiles_serdan"),
(7,"El Rosario","ic_el_rosario"),
(8,"Const. de 1917","ic_const_1917"),
(8,"U.A.M. I","ic_uami"),
(8,"C. de la Estrella","ic_c_de_la_estrella"),
(8,"Iztapalapa","ic_iztapalapa"),
(8,"Atlalilco","ic_atlalilco"),
(8,"Escuadrón 201","ic_escuadron_201"),
(8,"Aculco","ic_aculco"),
(8,"Apatlaco","ic_apatlaco"),
(8,"Iztacalco","ic_iztacalco"),
(8,"Coyuya","ic_coyuya"),
(8,"Santa Anita","ic_santa_anita"),
(8,"La Viga","ic_la_viga"),
(8,"Chabacano","ic_chabacano"),
(8,"Obrera","ic_obrera"),
(8,"Doctores","ic_doctores"),
(8,"Isabel la Católica","ic_isabel_catolica"),
(8,"Salto del Agua","ic_salto_del_agua"),
(8,"San Juan de Letrán","ic_san_juan_letran"),
(8,"Bellas Artes","ic_bellas_artes"),
(8,"Garibaldi / Lagunilla","ic_garibaldi_lagunilla"),
(9,"Tacubaya","ic_tacubaya"),
(9,"Patriotismo","ic_patriotismo"),
(9,"Chilpancingo","ic_chilpancingo"),
(9,"Centro Médico","ic_centro_medico"),
(9,"Lázaro Cárdenas","ic_lazaro_cardenas"),
(9,"Chabacano","ic_chabacano"),
(9,"Jamaica","ic_jamaica"),
(9,"Mixiuhca","ic_mixiuhca"),
(9,"Velódromo","ic_velodromo"),
(9,"Ciudad Deportiva","ic_ciudad_deportiva"),
(9,"Puebla","ic_puebla"),
(9,"Pantitlán","ic_pantitlan"),
(10,"Pantitlán","ic_pantitlan"),
(10,"Agrícola Oriental","ic_agricola_oriental"),
(10,"Canal de San Juan","ic_canal_de_san_juan"),
(10,"Tepalcates","ic_tepalcates"),
(10,"Guelatao","ic_guelatao"),
(10,"Peñón viejo","ic_peñon_viejo"),
(10,"Acatitla","ic_acatitla"),
(10,"Santa Marta","ic_santa_marta"),
(10,"Los Reyes","ic_los_reyes"),
(10,"La Paz","ic_la_paz"),
(11,"Buenavista","ic_buenavista"),
(11,"Guerrero","ic_guerrero"),
(11,"Garibaldi / Lagunilla","ic_garibaldi_lagunilla"),
(11,"Lagunilla","ic_lagunilla"),
(11,"Tepito","ic_tepito"),
(11,"Morelos","ic_morelos"),
(11,"San Lázaro","ic_san_lazaro"),
(11,"Flores Magón","ic_flores_magon"),
(11,"Romero Rubio","ic_romero_rubio"),
(11,"Oceanía","ic_oceania"),
(11,"Deportivo Oceanía","ic_deportivo_oceania"),
(11,"Villa de Aragón","ic_villa_de_aragon"),
(11,"Nezahualcóyotl","ic_nezahualcoyotl"),
(11,"Impulsora","ic_impulsora"),
(11,"Río de los Remedios","ic_rio_de_los_remedios"),
(11,"Múzquiz","ic_muzquiz"),
(11,"Ecatepec","ic_ecatepec"),
(11,"Olímpica","ic_olimpica"),
(11,"Plaza Aragón","ic_plaza_aragon"),
(11,"Ciudad Azteca","ic_ciudad_azteca"),
(12,"Mixcoac","ic_mixcoac"),
(12,"Insurgentes Sur","ic_insurgentes_sur"),
(12,"Hospital 20 de Noviembre","ic_hospital_20_de_noviembre"),
(12,"Zapata","ic_zapata"),
(12,"Parque de los Venados","ic_parque_de_los_venados"),
(12,"Eje Central","ic_eje_central"),
(12,"Ermita","ic_ermita"),
(12,"Mexicaltzingo","ic_mexicaltzingo"),
(12,"Atlalilco","ic_atlalilco"),
(12,"Culhuacán","ic_culhuacan"),
(12,"San Andrés Tomatlán","ic_san_andres_tomatlan"),
(12,"Lomas Estrella","ic_lomas_estrella"),
(12,"Calle 11","ic_calle_11"),
(12,"Periférico Ote.","ic_periferico_ote"),
(12,"Tezonco","ic_tezonco"),
(12,"Olivos","ic_olivos"),
(12,"Nopalera","ic_nopalera"),
(12,"Zapotitlán","ic_zapotitlan"),
(12,"Tlaltenco","ic_tlaltenco"),
(12,"Tláhuac","ic_tlahuac");