-- MySQL Script generated by MySQL Workbench
-- Thu 28 Jan 2021 03:49:40 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metro` ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `metro` ;

-- -----------------------------------------------------
-- Table `metro`.`linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`linea` (
  `id_Linea` INT NOT NULL AUTO_INCREMENT,
  `linea` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Linea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metro`.`estacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`estacion` (
  `id_estacion` INT NOT NULL AUTO_INCREMENT,
  `estacion` VARCHAR(45) NULL,
  `id_Linea` INT NOT NULL,
  PRIMARY KEY (`id_estacion`),
  INDEX `fk_Estacion_Linea_idx` (`id_Linea` ASC) VISIBLE,
  CONSTRAINT `fk_Estacion_Linea`
    FOREIGN KEY (`id_Linea`)
    REFERENCES `metro`.`linea` (`id_Linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
